### ISSUE TITLE
Discussion: u32 default?

### ISSUE THREAD

**Issue by DavidJFelix** [contain-rs/bit-vec#20]
Not really a bug but I wanted to bring this up. [In the bitvec struct](https://github.com/contain-rs/bit-vec/blob/master/src/lib.rs#L193) the default storage size is u32. I typically use it with `u8` but I appreciate the use of `u32` or a higher size storage since this is allows register alignment. However, shouldn't it be `usize` to account for the wordsize on 64bit processors as well as 32bit?

**Comment by Gankro** [comment]
Until a couple days ago usize wasn't a supported option -- actually several months ago it was the *only* option (blocks weren't exposed) but it was changed to use u32 as part of std's "needlessly pointer-sized integers" cleanup.

I only exposed the blocks as part of the API so that it could be built on via BitSet and so on.

Have you actually benchmarked any perf differences between usize/u32/u8?

**Comment by DavidJFelix** [comment]
I have not benchmarked them in rust, but I'm porting a C program over to Rust that I have benchmarked. The CPU I tested it on in C did have a (very) minor performance improvement in general use. The issue with benchmarking something like this is that the CPU could do a lot of things to hide any benefit. For example, if I'm using `u8` as the storage block and I have to read 64 bits, I'd see 8 `mov`s in asm followed by 64 bits worth of checks. Most modern processors will notice that the 8 `mov`s are independent and can be pipelined. Since a bulk of the work will be done in actually checking, the difference between 8 `movb` and 1 `movq` will largely disappear in a linear use case. However, since you're intentionally not aligning to register size, you're going to have an issue. In x86, if you're using byte registers or word (16b) registers, you'll only be using some of your register space. What this means is you have to do `mov`s, then process, do `mov`s, then process, etc, because you're wasting register space. If all you're doing is processing, though... this problem goes away with pipelining.

![](http://www.cs.virginia.edu/~evans/cs216/guides/x86-registers.png)

With the above graph, suppose we have a VERY large bitvec and we're processing it in parts. If we `mov` into the byte sized portions of EAX, EBX, ECX and EDX (using AL, AH, BL, BH, CL, CH, DL, DH) then begin processing, we'll process the A registers and once we move to the B processors, a `mov` to the A registers could potentially begin. However -- in real code it isn't nearly this simple. Our waste could be noticed if the "processing" portion of our code is more than just modifications. Jumps to further logic could require the registers that we're wastefully using. We may not be able to pipeline the subsequent `movs` due to jump logic and whatever branch prediction that occurs. Keep in mind also that occupying AL or AH prevents use of EAX for 32b storage.

All of the above was an example case for using x86, which would probably be fine with `u32`... however, the issues above with choosing `u16` or `u8` in a 32bit environment are the same as using `u32` in a 64bit environment. This is why I suggest `usize`.

I'm using `u8` because I only ever access 1 byte at a time. This means that I actually free up a 16bit and 8bit register in a 32bit environment, or a 32bit, 16bit and 8bit register in 64bit environment.

Like I said, this is really just a discussion. I don't know what's best for the average case, it just feels like `u32` imposes awkwardly. My leaning is toward an extreme like `u8` or `usize`, but perhaps all of this is just bikeshedding.

**Comment by DavidJFelix** [comment]
Any further thoughts on this @Gankro? I just started to look at this again. I can close the issue if you're unconvinced.

**Comment by Gankro** [comment]
Oh sorry, not long after I went into a deep grind to finish my thesis, which is due in 2 weeks! I'm afraid I'm a bit useless until then.

I'd prefer to stick with u32 to avoid being needlessly platform-dependent *unless* someone does some benchmarks and demonstrates that there's a significant difference.

**Comment by DavidJFelix** [comment]
No problem at all. I'll close it pending further discussion.
