### ISSUE TITLE
Publish 0.4.2?

### ISSUE THREAD

**Issue by dpc** [contain-rs/bit-vec#26]
I'd like to publish a new version of mioco and it depends on the recent fix for usize. Could you push a new version to crates.io?

**Comment by pczarn** [comment]
0.4.2 published.

**Comment by dpc** [comment]
Thanks!

**Comment by dpc** [comment]
https://crates.io/crates/bit-vec still shows 0.4.1

**Comment by pczarn** [comment]
Oh, I don't have permissions to publish, @Gankro has

**Comment by Gankro** [comment]
Published (but any owner of contain-rs should have been able to).
