### ISSUE TITLE
Set/unset bits iterator

### ISSUE THREAD

**Issue by saik0** [contain-rs/bit-vec#44]
We could use [leading_zeros](https://doc.rust-lang.org/std/primitive.usize.html#method.leading_zeros) or [trailing_zeros](https://doc.rust-lang.org/std/primitive.usize.html#method.trailing_zeros) to iterate over the indices of set or unset bits, avoiding lots of arithmetic/shifting.

I could whip up a PR if it's decided it's worth adding.

**Comment by pczarn** [comment]
I believe this is implemented in `bit-set`, though impovements to its speed would be welcome.
