### ISSUE TITLE
Add shrink_to_fit and split_off methods

### ISSUE THREAD

**Issue by clarfon** [contain-rs/bit-vec#45]
These are ones that `Vec` has that would also make sense on `BitVec`. Unfortunately, the latter is much harder to implement.

**Comment by pczarn** [comment]
The split_off is now implemented and enabled. Whereas shrink_to_fit was added in https://github.com/contain-rs/bit-vec/commit/1e30837caa75f2b64327777c03039c16b2fc06ce
