### ISSUE TITLE
`set_all` slow?

### ISSUE THREAD

**Issue by burdges** [contain-rs/bit-vec#55]
I noticed a regression in https://github.com/w3f/vdf/commit/961caee8c9730f5b245ef6e3492d358e1a29fb44 which indicates `set_all` being slower than an allocation.  Is it perhaps that the allocation is being optimized away, but the for loop in `set_all` has some overhead?

**Comment by pczarn** [comment]
You can only know for sure if you inspect the generated LLVM IR or assembly. For how many iterations does the loop run?

**Comment by burdges** [comment]
It's looking for 2048 bit primes, so if the loop was not optimized then you'd expect it to average around 1400 iterations, but the optimizations should improve this, including the sieve using bit-vec.

**Comment by pczarn** [comment]
I added a benchmark which illustrates the point. Found no apparent issue, so I'm closing.

Thank you for the lead, @burdges , regardless.
