### ISSUE TITLE
Push new documentation

### ISSUE THREAD

**Issue by BenWiederhake** [contain-rs/bit-vec#67]
I'd like to xor two bitvecs. [The documentation](https://contain-rs.github.io/bit-vec/bit_vec/struct.BitVec.html) suggests there is no such method. However, the latest release *does* contain the [`xor`](https://github.com/contain-rs/bit-vec/blob/master/src/lib.rs#L782) method. In other words: The documentation is outdated.

Please rebuild and re-upload, thanks!

(And thanks for the nice crate! No additional dependencies, just what I like to see.)

**Comment by pczarn** [comment]
I added a link to docs.rs instead.
