### ISSUE TITLE
Infinite recursion issue

### ISSUE THREAD

**Issue by snawaz** [contain-rs/bit-vec#76]
The implementation of `count_ones()` does not make sense. It's actually an infinite recursion. Or is this intended? Or a bug? If intended, what is it supposed to do? Is it not infinite, or am I reading the code correctly? 

https://github.com/contain-rs/bit-vec/blob/d3585be9e5057eee56f81fe3d5d958669bd7db74/src/lib.rs#L153-L164

**Comment by pczarn** [comment]
The code is OK. Inherent methods have higher priority; an inherent method is called, not the trait declared method.

Here is an explanation: https://doc.rust-lang.org/reference/expressions/method-call-expr.html

Relevant part of the above explanation:

> Then, for each candidate type T, search for a [visible](https://doc.rust-lang.org/reference/visibility-and-privacy.html) method with a receiver of that type in the following places:
>
> * T's inherent methods (methods implemented directly on T).
> * Any of the methods provided by a [visible](https://doc.rust-lang.org/reference/visibility-and-privacy.html) trait implemented by T. If T is a type parameter, methods provided by trait bounds on T are looked up first. Then all remaining methods in scope are looked up.
>
> Note: the lookup is done for each type in order, which can occasionally lead to surprising results.

Example code:

```rust
trait BitBlock: Copy {
    fn count_ones(self) -> u32;
}

impl BitBlock for u64 {
    fn count_ones(self) -> u32 { self.count_ones() }
}

fn main() {
    let r = BitBlock::count_ones(123u64);
    println!("Hello, world! {}", r); // => Hello, world! 6
}
```

**Comment by pczarn** [comment]
Thanks for taking the time to dig into the code; closing as not an issue.

**Comment by pczarn** [comment]
@snawaz feel free to open a PR adding a comment above the call, to explain it

**Comment by snawaz** [comment]
> The code is OK. Inherent methods have higher priority; an inherent method is called, not the trait declared method.
> 
> Here is an explanation: https://doc.rust-lang.org/reference/expressions/method-call-expr.html

Ohh, I was not aware of the fact that the built-in integral types (such as `u32`, `u64` etc) have [`count_ones()` method][1] on them!  Thanks for the quick response to this issue (which is a non-issue now). Thanks for closing it.

[1]: https://doc.rust-lang.org/std/primitive.u64.html#method.count_ones
